spring:
  application:
    name: user
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
  datasource:
    username: oge
    password: ypfamily608
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://125.220.153.23:30865/oge
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: http://125.220.153.22:9006
  accessKey: rssample
  secretKey: ypfamily608

server:
  port: 19087
  tomcat:
    max-swallow-size: -1
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
  servlet:
    context-path: /gds
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*